// Player configuration
export const PLAYER_HEALTH = 3;
export const PLAYER_MOVEMENT_HORIZONTAL_VELOCITY = 500;
export const PLAYER_BULLET_MAX_COUNT = 25; // Increased from 10 to 25
export const PLAYER_BULLET_INTERVAL = 300;
export const PLAYER_BULLET_SPEED = 300;
export const PLAYER_BULLET_LIFESPAN = 3000;
export const PLAYER_SECONDARY_BULLET_MAX_COUNT = 10; // Secondary weapon ammo
export const PLAYER_LIVES = 3;

// Enemy configuration
export const ENEMY_SCOUT_HEALTH = 2;
export const ENEMY_SCOUT_MOVEMENT_VERTICAL_VELOCITY = 100;
export const ENEMY_SCOUT_MOVEMENT_HORIZONTAL_VELOCITY = 80;
export const ENEMY_SCOUT_MOVEMENT_MAX_X = 40;
export const ENEMY_SCOUT_SCORE = 100;
export const ENEMY_SCOUT_GROUP_SPAWN_INTERVAL = 5000;
export const ENEMY_SCOUT_GROUP_SPAWN_START = 1000;

export const ENEMY_FIGHTER_HEALTH = 1;
export const ENEMY_FIGHTER_MOVEMENT_VERTICAL_VELOCITY = 120;
export const ENEMY_FIGHTER_SCORE = 200;
export const ENEMY_FIGHTER_GROUP_SPAWN_INTERVAL = 6000;
export const ENEMY_FIGHTER_GROUP_SPAWN_START = 3000;
export const ENEMY_FIGHTER_BULLET_MAX_COUNT = 5;
export const ENEMY_FIGHTER_BULLET_INTERVAL = 800;
export const ENEMY_FIGHTER_BULLET_SPEED = -200;
export const ENEMY_FIGHTER_BULLET_LIFESPAN = 3000;

// Component configuration
export const COMPONENT_MOVEMENT_HORIZONTAL_DRAG = 0.1;
export const COMPONENT_MOVEMENT_HORIZONTAL_MAX_VELOCITY = 500;
export const COMPONENT_MOVEMENT_VERTICAL_DRAG = 0.1;
export const COMPONENT_MOVEMENT_VERTICAL_MAX_VELOCITY = 500;
